// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shopapp.data.Concrete;

namespace shopapp.data.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20220123152002_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("shopapp.entity.Arrangement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Content")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Arrangement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = 4
                        });
                });

            modelBuilder.Entity("shopapp.entity.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("shopapp.entity.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Laptop",
                            Url = "laptop"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Masaüstü Bilgisayar",
                            Url = "bilgisayar"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Tablet",
                            Url = "tablet"
                        });
                });

            modelBuilder.Entity("shopapp.entity.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.1 İnç</b> Ekran boyutu, <b>64 GB</b> Dahili depolama, <b>3GB</b> Ram, <b>12 MP</b> Kamera çözünürlüğü, <b>2942 mAh</b> Batarya kapasitesine sahip bir <b>Apple</b> telefon ürünüdür.",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Apple iPhone Xr",
                            Price = 8923.0,
                            Rating = 5.0,
                            Stock = 4,
                            Url = "apple-iphone-xr"
                        },
                        new
                        {
                            ProductId = 2,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.7 İnç</b> Ekran boyutu, <b>128 GB</b> Dahili depolama, <b>6 GB </b> Ram, <b>12 MP</b> Kamera çözünürlüğü, <b>4352 mAh</b> Batarya kapasitesine sahip bir <b>Apple</b> telefon ürünüdür.",
                            ImageUrl = "2.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "iPhone 13 Pro Max",
                            Price = 24499.0,
                            Rating = 5.0,
                            Stock = 3,
                            Url = "iphone-13-pro-max"
                        },
                        new
                        {
                            ProductId = 3,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.6 İnç</b> Ekran boyutu, <b>128 GB</b> Dahili depolama, <b>8 GB</b> Ram, <b>64 MP</b> Kamera çözünürlüğü, <b>5000 mAh</b> Batarya kapasitesine sahip bir <b>Xiaomi</b> telefon ürünüdür.",
                            ImageUrl = "3.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Poco X3 GT",
                            Price = 4749.0,
                            Rating = 4.0,
                            Stock = 7,
                            Url = "poxo-x3-gt"
                        },
                        new
                        {
                            ProductId = 4,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.5 İnç</b> Ekran boyutu,<b>128 GB</b> Dahili depolama, <b>6GB Ram</b>, <b>12 MP</b> Kamera çözünürlüğü, <b>4500 mAh</b> Batarya kapasitesine sahip bir <b>Samsung</b> telefon ürünüdür.",
                            ImageUrl = "4.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Samsung Galaxy S20 Fe",
                            Price = 6785.0,
                            Rating = 4.5,
                            Stock = 4,
                            Url = "samsung-galaxy-s20"
                        },
                        new
                        {
                            ProductId = 5,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.4 İnç</b> Ekran boyutu, <b>128 GB</b> Dahili depolama, <b>6 GB</b> Ram, <b>64 MP</b> Kamera çözünürlüğü, <b>5000 mAh</b> Batarya kapasitesine sahip bir <b>Samsung</b> telefon ürünüdür.",
                            ImageUrl = "5.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Samsung Galaxy A32",
                            Price = 3921.0,
                            Rating = 4.0,
                            Stock = 8,
                            Url = "samsung-galaxy-s32"
                        },
                        new
                        {
                            ProductId = 6,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.7 İnç</b> Ekran boyutu, <b>128 GB</b> Dahili depolama, <b>6 GB</b> Ram, <b>12 MP</b> Kamera çözünürlüğü, <b>3687 mAh</b> Batarya kapasitesine sahip bir <b>Apple</b> telefon ürünüdür.",
                            ImageUrl = "6.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "iPhone 12 Pro Max",
                            Price = 20579.0,
                            Rating = 5.0,
                            Stock = 4,
                            Url = "iphone-12-pro-max"
                        },
                        new
                        {
                            ProductId = 7,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.4 İnç</b> Ekran boyutu, <b>128 GB</b> Dahili depolama, <b>8 GB</b> Ram, <b>48 MP</b> Kamera çözünürlüğü, <b>4310 mAh</b> Batarya kapasitesine sahip bir <b>Oppo</b> telefon ürünüdür.",
                            ImageUrl = "7.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Oppo Reno 5 Lite",
                            Price = 4399.0,
                            Rating = 3.5,
                            Stock = 10,
                            Url = "oppo-reno-5-lite"
                        },
                        new
                        {
                            ProductId = 8,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.6 İnç</b> Ekran boyutu, <b>128 GB</b> Dahili depolama, <b>6 GB</b> Ram, <b>48 MP</b> Kamera çözünürlüğü, <b>5000 mAh</b> Batarya kapasitesine sahip bir <b>General Mobile</b> telefon ürünüdür.",
                            ImageUrl = "8.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "General Mobile Gm21 Pro",
                            Price = 3233.0,
                            Rating = 3.0,
                            Stock = 10,
                            Url = "general-mobile-gm21-pro"
                        },
                        new
                        {
                            ProductId = 9,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.5 İnç</b> Ekran boyutu, <b>32 GB</b> Dahili depolama, <b>3 GB</b> Ram, <b>13 MP</b> Kamera çözünürlüğü, <b>5020 mAh</b> Batarya kapasitesine sahip bir <b>Xiaomi</b> telefon ürünüdür.",
                            ImageUrl = "9.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Xiaomi Redmi 9",
                            Price = 2950.0,
                            Rating = 4.5,
                            Stock = 5,
                            Url = "xiaomi-redmi-9"
                        },
                        new
                        {
                            ProductId = 10,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.4 İnç</b> Ekran boyutu, <b>128 GB</b> Dahili depolama, <b>4 GB</b> Ram, <b>48 MP</b> Kamera çözünürlüğü, <b>5000 mAh</b> Batarya kapasitesine sahip bir <b>Oppo</b> telefon ürünüdür.",
                            ImageUrl = "10.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Oppo A74",
                            Price = 3299.0,
                            Rating = 4.5,
                            Stock = 6,
                            Url = "oppo-a74"
                        },
                        new
                        {
                            ProductId = 11,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.6 İnç</b> Ekran boyutu, <b>256 GB</b> Dahili depolama, <b>8 GB</b> Ram, <b>108 MP</b> Kamera çözünürlüğü, <b>5000 mAh</b> Batarya kapasitesine sahip bir <b>Xiaomi</b> telefon ürünüdür.",
                            ImageUrl = "11.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Xiaomi Mi 11T",
                            Price = 9799.0,
                            Rating = 4.5,
                            Stock = 5,
                            Url = "xiaomi-mi-11t"
                        },
                        new
                        {
                            ProductId = 12,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.4 İnç</b> Ekran boyutu, <b>128 GB</b> Dahili depolama, <b>4 GB</b> Ram, <b>48 MP</b> Kamera çözünürlüğü, <b>5000 mAh</b> Batarya kapasitesine sahip bir <b>Oppo</b> telefon ürünüdür.",
                            ImageUrl = "12.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Oppo Realme 8 Pro",
                            Price = 3299.0,
                            Rating = 3.5,
                            Stock = 10,
                            Url = "oppo-realme-8-pro"
                        },
                        new
                        {
                            ProductId = 13,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>6.7 İnç</b> Ekran boyutu, <b>128 GB</b> Dahili depolama, <b>8 GB</b> Ram, <b>12 MP</b> Kamera çözünürlüğü, <b>4800 mAh</b> Batarya kapasitesine sahip bir <b>Samsung</b> telefon ürünüdür.",
                            ImageUrl = "31.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Samsung Galaxy S21 Plus",
                            Price = 13885.0,
                            Rating = 5.0,
                            Stock = 8,
                            Url = "samsung-galaxy-s21-plus"
                        },
                        new
                        {
                            ProductId = 14,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>16.1 İnç</b> Ekran boyutu, <b>1920x1080 Piksel</b> Ekran çözünürlüğü, <b>Amd Ryzen 5 4600H</b> İşlemcisi <b>16 GB</b> Ram, <b>512 GB SSD</b> Depolamaya sahip sahip bir <b>Huawei</b> laptop ürünüdür.",
                            ImageUrl = "13.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Huawei Matebook D 16",
                            Price = 10499.0,
                            Rating = 5.0,
                            Stock = 7,
                            Url = "huawei-matebook-d-16"
                        },
                        new
                        {
                            ProductId = 15,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>14 İnç</b> Ekran boyutu, <b>2160x1440 Piksel</b> Ekran çözünürlüğü, <b>Amd Ryzen 5 4600 H</b> İşlemcisi <b>8 GB</b> Ram, <b>256 GB SSD</b> Depolamaya sahip sahip bir <b>Huawei</b> laptop ürünüdür.",
                            ImageUrl = "14.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Huawei Matebook 14",
                            Price = 9499.0,
                            Rating = 4.0,
                            Stock = 10,
                            Url = "huawei-matebook-14"
                        },
                        new
                        {
                            ProductId = 16,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>15.6 İnç</b> Ekran boyutu, <b>1920x1080 Piksel</b> Ekran çözünürlüğü, <b>İntel Core i5</b> İşlemcisi <b>16 GB</b> Ram, <b>512 GB SSD</b> Depolamaya sahip sahip bir <b>Huawei</b> laptop ürünüdür.",
                            ImageUrl = "15.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Huawei Matebook 15 Core",
                            Price = 7008.0,
                            Rating = 4.5,
                            Stock = 9,
                            Url = "huawei-matebook-15-core"
                        },
                        new
                        {
                            ProductId = 17,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>16.2 İnç</b> Ekran boyutu, <b>3456x2234 Piksel</b> Ekran çözünürlüğü, <b>Apple M1 Pro</b> İşlemcisi <b>16 GB</b> Ram, <b>512 GB SSD</b> Depolamaya sahip sahip bir <b>Apple</b> laptop ürünüdür.",
                            ImageUrl = "16.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Macbook Pro MK183TU/A M1 Pro",
                            Price = 16423.0,
                            Rating = 4.0,
                            Stock = 7,
                            Url = "macbook-pro-m1-pro"
                        },
                        new
                        {
                            ProductId = 18,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>15.6 İnç</b> Ekran boyutu, <b>1920x1080 Piksel</b> Ekran çözünürlüğü, <b>İntel Core i7</b> İşlemcisi <b>16 GB</b> Ram, <b>512 GB SSD</b> Depolamaya sahip sahip bir <b>Asus</b> laptop ürünüdür.",
                            ImageUrl = "17.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Asus Rog Strix G15",
                            Price = 27690.0,
                            Rating = 4.0,
                            Stock = 11,
                            Url = "asus-rog-strix-g15"
                        },
                        new
                        {
                            ProductId = 19,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>15.6 İnç</b> Ekran boyutu, <b>1920x1080 Piksel</b> Ekran çözünürlüğü, <b>İntel Core i3</b> İşlemcisi <b>8 GB</b> Ram, <b>256 GB SSD</b> Depolamaya sahip sahip bir <b>Honor</b> laptop ürünüdür.",
                            ImageUrl = "18.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Honor Magic Book X15 Core",
                            Price = 8539.0,
                            Rating = 4.0,
                            Stock = 12,
                            Url = "honor-magic-book-x15-core"
                        },
                        new
                        {
                            ProductId = 20,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>13.9 İnç</b> Ekran boyutu, <b>3000x2000 Piksel</b> Ekran çözünürlüğü, <b>İntel Core i7</b> İşlemcisi <b>16 GB</b> Ram, <b>1 TB SSD</b> Depolamaya sahip sahip bir <b>Huawei</b> laptop ürünüdür.",
                            ImageUrl = "19.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Huawei Matebook X Pro",
                            Price = 18499.0,
                            Rating = 4.5,
                            Stock = 6,
                            Url = "huawei-matebook-x-pro"
                        },
                        new
                        {
                            ProductId = 21,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>15.6 İnç</b> Ekran boyutu, <b>1920x1080 Piksel</b> Ekran çözünürlüğü, <b>İntel Core i5</b> İşlemcisi <b>8 GB</b> Ram, <b>256 GB SSD</b> Depolamaya sahip sahip bir <b>Monster</b> laptop ürünüdür.",
                            ImageUrl = "20.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Monster Abra A5 V16",
                            Price = 11299.0,
                            Rating = 5.0,
                            Stock = 4,
                            Url = "monster-abra-a5-v16"
                        },
                        new
                        {
                            ProductId = 22,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>17.3 İnç</b> Ekran boyutu, <b>2560x1440 Piksel</b> Ekran çözünürlüğü, <b>İntel Core i7</b> İşlemcisi <b>32 GB</b> Ram, <b>1 TB SSD</b> Depolamaya sahip sahip bir <b>Msi</b> laptop ürünüdür.",
                            ImageUrl = "21.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Msi GE76 Raider 11UH",
                            Price = 41282.0,
                            Rating = 5.0,
                            Stock = 5,
                            Url = "msi-ge76-raider-11uh"
                        },
                        new
                        {
                            ProductId = 23,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>16 İnç</b> Ekran boyutu, <b>2560x1440 Piksel</b> Ekran çözünürlüğü, <b>İntel Core i9</b> İşlemcisi <b>32 GB</b> Ram, <b>4 TB SSD</b> Depolamaya sahip sahip bir <b>Casper</b> laptop ürünüdür.",
                            ImageUrl = "22.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Casper Excalibur G911",
                            Price = 24699.0,
                            Rating = 4.5,
                            Stock = 8,
                            Url = "casper-excalibur-g911"
                        },
                        new
                        {
                            ProductId = 24,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>15.6 İnç</b> Ekran boyutu, <b>1920x1080 Piksel</b> Ekran çözünürlüğü, <b>İntel Core i7</b> İşlemcisi <b>16 GB</b> Ram, <b>512 GB SSD</b> Depolamaya sahip sahip bir <b>Msi</b> laptop ürünüdür.",
                            ImageUrl = "23.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Msi GP66 Leopard 11UG",
                            Price = 35515.0,
                            Rating = 5.0,
                            Stock = 5,
                            Url = "msi-gp66-leopard-11ug"
                        },
                        new
                        {
                            ProductId = 25,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>ATX</b> Anakartlar için, <b>10 Adet</b> Fan kapasitesi, <b>2 Adet</b> Harddisk kapasitesi, <b>6.75 Kg</b> Ağırlığa sahip sahip bir <b>Thermaltake</b> Masaüstü Bilgisayar ürünüdür.",
                            ImageUrl = "24.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Thermaltake Level 20 MT",
                            Price = 1444.0,
                            Rating = 5.0,
                            Stock = 6,
                            Url = "thermaltake-level-20-mt"
                        },
                        new
                        {
                            ProductId = 26,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>ATX</b> Anakartlar için, <b>6 Adet</b> Fan kapasitesi, <b>3 Adet</b> Harddisk kapasitesi, <b>5.6 Kg</b> Ağırlığa sahip sahip bir <b></b> Masaüstü Bilgisayar ürünüdür.",
                            ImageUrl = "25.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Msi Mag Forge Kasa",
                            Price = 927.0,
                            Rating = 4.5,
                            Stock = 9,
                            Url = "msi-mag-forge-100mm"
                        },
                        new
                        {
                            ProductId = 27,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>ATX</b> Anakartlar için, <b>10 Adet</b> Fan kapasitesi, <b>2 Adet</b> Harddisk kapasitesi, <b>6.75 Kg</b> Ağırlığa sahip sahip bir <b>Thermaltake</b> Masaüstü Bilgisayar ürünüdür.",
                            ImageUrl = "26.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "Power Boost VK-T01B",
                            Price = 1349.0,
                            Rating = 4.5,
                            Stock = 12,
                            Url = "power-boost-vk-t01b"
                        },
                        new
                        {
                            ProductId = 28,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>ATX</b> Anakartlar için, <b>6 Adet</b> Fan kapasitesi, <b>1 HDD + 1 SSD</b> kapasitesi, <b>4.7 Kg</b> Ağırlığa sahip sahip bir <b>Gameforce</b> Masaüstü Bilgisayar ürünüdür.",
                            ImageUrl = "27.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Gameforce GF-8307 Glass 4X120M",
                            Price = 12000.0,
                            Rating = 5.0,
                            Stock = 9,
                            Url = "gameforce-gf-8307-glass-4x120m"
                        },
                        new
                        {
                            ProductId = 29,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>10.4 İnç</b> Ekran boyutu, <b>64 GB</b> Dahili depolama, <b>4 GB</b> Ram, <b>8 MP</b> Kamera çözünürlüğü, <b>7040 mAh</b> Batarya kapasitesine sahip bir <b>Samsung</b> tablet ürünüdür.",
                            ImageUrl = "28.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Samsung Galaxy Tab S6 Lite",
                            Price = 3795.0,
                            Rating = 5.0,
                            Stock = 5,
                            Url = "samsung-galaxy-tab-s6-lite"
                        },
                        new
                        {
                            ProductId = 30,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>10.1 İnç</b> Ekran boyutu, <b>64 GB</b> Dahili depolama, <b>4 GB</b> Ram, <b>8 MP</b> Kamera çözünürlüğü, <b>5000 mAh</b> Batarya kapasitesine sahip bir <b>Lenovo</b> tablet ürünüdür.",
                            ImageUrl = "29.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Lenovo Tab m10 Mtk Helio",
                            Price = 2099.0,
                            Rating = 4.5,
                            Stock = 7,
                            Url = "lenovo-tab-m10-mtk-helio"
                        },
                        new
                        {
                            ProductId = 31,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>8.7 İnç</b> Ekran boyutu, <b>32 GB</b> Dahili depolama, <b>3 GB</b> Ram, <b>8 MP</b> Kamera çözünürlüğü, <b>5100 mAh</b> Batarya kapasitesine sahip bir <b>Samsung</b> tablet ürünüdür.",
                            ImageUrl = "30.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Samsung Galaxy Tab A7 Lite",
                            Price = 1427.0,
                            Rating = 5.0,
                            Stock = 5,
                            Url = "samsung-galaxy-tab-a7-lite"
                        },
                        new
                        {
                            ProductId = 32,
                            DateAdded = "23.01.2022 18:20:01",
                            Description = "<b>8.3 İnç</b> Ekran boyutu, <b>64 GB</b> Dahili depolama, <b>4 GB</b> Ram, <b>12 MP</b> Kamera çözünürlüğü, <b>5124 mAh</b> Batarya kapasitesine sahip bir <b>Apple</b> tablet ürünüdür.",
                            ImageUrl = "32.jpg",
                            IsApproved = true,
                            IsHome = true,
                            Name = "Apple iPad mini",
                            Price = 7099.0,
                            Rating = 5.0,
                            Stock = 6,
                            Url = "apple-ipad-mini"
                        });
                });

            modelBuilder.Entity("shopapp.entity.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("shopapp.entity.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            ImageUrl = "slider1.png",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            ImageUrl = "slider2.png",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            ImageUrl = "slider3.png",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            ImageUrl = "slider4.png",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            ImageUrl = "slider5.png",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            ImageUrl = "slider6.png",
                            Order = 6
                        });
                });

            modelBuilder.Entity("shopapp.entity.Cart", b =>
                {
                    b.HasOne("shopapp.entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("shopapp.entity.ProductCategory", b =>
                {
                    b.HasOne("shopapp.entity.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shopapp.entity.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("shopapp.entity.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("shopapp.entity.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
